### ISSUE TITLE
only 9 concepts? 

### ISSUE THREAD

**Issue by SimonGreenhill** [lingpy/language-island-paper#1]
Why are there only 9 concepts identified by the [CLDF](https://github.com/lingpy/language-island-paper/blob/master/src/lexibank_hantganbangime/cldf/parameters.csv)?

**Comment by xrotwang** [comment]
It seems only the first character of the concept ID is used:
https://github.com/lingpy/language-island-paper/blob/7d211b50741664dc2ac347ee4312f1600e5430c9/src/lexibank_hantganbangime/__init__.py#L52
resulting in only `range(1, 9)` showing up as `Parameter_ID`, thus only 9 concepts have forms.

**Comment by SimonGreenhill** [comment]
Yep, I pushed a fix here: https://github.com/lingpy/language-island-paper/pull/2
